img_dir = './data/segmentation_full/images'
mask_dir ='./data/segmentation_full/masks'
out_dir = './runs'
# img_dir = '../data/segmentation/images'
# mask_dir ='../data/segmentation/masks'
n_epochs = 100
n_classes = 1
# classes = ['Broccoli']
classes = ['ear', 'ear_sub']
device_ids = [0,1,2,3]
batch_size = 6
lr = 0.0002
beta_1 = 0.5
beta_2 = 0.999
im_size = 1500
